local debugger = nil;

function init(self)
	debugger = Debugger:new()
	debugger:printer(1, "Test")
	debugger:printer(self)
	debugger:printerinit(self, "Test1")
	debugger:printer("Test2")
end

--[[function final(self)
	
end

function update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
]]